build:
   image: docker:latest
   services:
   - docker:dind
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
     - docker build -t registry.gitlab.com/ridiculous-eagle/neural-style-transfer:$CI_JOB_ID .
     - docker push registry.gitlab.com/ridiculous-eagle/neural-style-transfer:$CI_JOB_ID