build:

  image: docker:latest

  services:
   - docker:dind

  variables:
    CONTAINER_IMAGE: registry.gitlab.com/ridiculous-eagle/neural-style-transfer

  stage: build

  script:
     - echo $CI_REGISTRY_IMAGE
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    # - docker build -t $CONTAINER_IMAGE:$CI_JOB_ID -t $CONTAINER_IMAGE .
    # - docker push $CONTAINER_IMAGE:$CI_JOB_ID
    # - docker push $CONTAINER_IMAGE